{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "811eb6cb",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dash app running on http://127.0.0.1:8050/\n"
     ]
    }
   ],
   "source": [
    "import base64\n",
    "import io\n",
    "import pandas as pd\n",
    "from dash import Dash, dcc, html, Input, Output\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "app = Dash(__name__)\n",
    "server = app.server   # IMPORTANT for deployment\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.H1(\"MK Dons - CEF Dashboard\"),\n",
    "\n",
    "    dcc.Upload(\n",
    "        id='upload-data',\n",
    "        children=html.Div(['Drag and Drop or ', html.A('Select Excel File')]),\n",
    "        style={\n",
    "            'width': '60%',\n",
    "            'height': '60px',\n",
    "            'lineHeight': '60px',\n",
    "            'borderWidth': '1px',\n",
    "            'borderStyle': 'dashed',\n",
    "            'borderRadius': '5px',\n",
    "            'textAlign': 'center',\n",
    "            'margin': '10px auto'\n",
    "        },\n",
    "        multiple=False\n",
    "    ),\n",
    "\n",
    "    html.Div(id='file-status'),\n",
    "\n",
    "    dcc.Dropdown(id='participant-dropdown', placeholder=\"Select a coach\", style={\"marginTop\": \"10px\"}),\n",
    "    dcc.Dropdown(id='block-dropdown', placeholder=\"Select a block\", style={\"marginTop\": \"10px\"}),\n",
    "\n",
    "    html.Div(id='group-grid', style={\"marginTop\": \"25px\"}),\n",
    "    dcc.Graph(id='question-chart'),\n",
    "\n",
    "    html.Hr(),\n",
    "\n",
    "    html.Div(id='development-lists', style={\"display\": \"flex\", \"gap\": \"40px\"}),\n",
    "\n",
    "    html.Hr(),\n",
    "    html.H2(\"Block Comparison\"),\n",
    "\n",
    "    html.Div([\n",
    "        html.Div([\n",
    "            dcc.Dropdown(id='compare-block-1', placeholder=\"Select first block\"),\n",
    "            html.Div(id='compare-grid-1')\n",
    "        ], style={\"width\": \"48%\", \"display\": \"inline-block\", \"verticalAlign\": \"top\"}),\n",
    "\n",
    "        html.Div([\n",
    "            dcc.Dropdown(id='compare-block-2', placeholder=\"Select second block\"),\n",
    "            html.Div(id='compare-grid-2')\n",
    "        ], style={\"width\": \"48%\", \"display\": \"inline-block\", \"float\": \"right\", \"verticalAlign\": \"top\"})\n",
    "    ])\n",
    "])\n",
    "\n",
    "# ===== Globals =====\n",
    "blocks = {}\n",
    "question_cols = []\n",
    "\n",
    "GROUP_LABELS = [\n",
    "    \"Understanding Self\",\n",
    "    \"Coaching Individuals\",\n",
    "    \"Coaching Practice\",\n",
    "    \"Skill Acquisition\",\n",
    "    \"MK Dons\",\n",
    "    \"Psychology/Social Support\",\n",
    "    \"Relationships\",\n",
    "    \"Athletic Development\",\n",
    "    \"Wellbeing/Lifestyle\"\n",
    "]\n",
    "\n",
    "QUESTION_TEXT = {\n",
    "1: \"Understands their role (IP/VEO)\",\n",
    "2: \"Engages with club coach CPD\",\n",
    "3: \"Effectively communicates (IP/VEO)\",\n",
    "4: \"Engages with players & parents informally (IP/VEO)\",\n",
    "5: \"Understands the game model\",\n",
    "6: \"Seeks to understand decisions (Q)\",\n",
    "7: \"Is positive and inspiring (IP)\",\n",
    "8: \"Sets realistic goals for players (IP/VEO)\",\n",
    "9: \"Use appropriate interventions (IP/VEO)\",\n",
    "10: \"Understands player differences\",\n",
    "11: \"Understands and applies LTPD\",\n",
    "12: \"Supports coaching with video and data (IP/VEO)\",\n",
    "13: \"Introduces sessions\",\n",
    "14: \"Embeds deliberate practice\",\n",
    "15: \"Creates action plans for players (IP)\",\n",
    "16: \"Debriefs sessions (IP/VEO)\",\n",
    "17: \"Uses club coaching methodology (IP)\",\n",
    "18: \"Adopts Club principles (H-O-P)\",\n",
    "19: \"Adopts multi-disc approach\",\n",
    "20: \"Aware of safeguarding policies/procedures\",\n",
    "21: \"Embeds competencies each session\",\n",
    "22: \"Notices changes in child's behaviour\",\n",
    "23: \"Signposts players to appropriate support (IP/VEO)\",\n",
    "24: \"Critical thinker who checks and challenges\",\n",
    "25: \"Manages other staff supporting sessions\",\n",
    "26: \"Listens and suspends judgement\",\n",
    "27: \"Has a recognised coaching cell (in club)\",\n",
    "28: \"Watches other coaches inside the club\",\n",
    "29: \"Embeds physical development\",\n",
    "30: \"Makes practice competitive & realistic\",\n",
    "31: \"Develops players physically through design\",\n",
    "32: \"Drives intensity using coaching strategies\",\n",
    "33: \"Reports issues using MyConcern appropriately\",\n",
    "34: \"Comfortable challenging poor practice\",\n",
    "35: \"Ambassador of MK Dons\",\n",
    "36: \"Has clear interests away from coaching\"\n",
    "}\n",
    "\n",
    "def get_colour(score):\n",
    "    if score >= 3.25:\n",
    "        return \"#4CAF50\"\n",
    "    elif score >= 2.51:\n",
    "        return \"#FFD966\"\n",
    "    elif score >= 1.75:\n",
    "        return \"#F4A261\"\n",
    "    else:\n",
    "        return \"#FF6B6B\"\n",
    "\n",
    "def parse_contents(contents):\n",
    "    content_type, content_string = contents.split(',')\n",
    "    decoded = base64.b64decode(content_string)\n",
    "    return pd.read_excel(io.BytesIO(decoded), header=None)\n",
    "\n",
    "def split_blocks(raw_df):\n",
    "    block_dfs = []\n",
    "    header_rows = raw_df[raw_df.apply(\n",
    "        lambda row: row.astype(str).str.strip().str.lower().eq(\"full name\").any(),\n",
    "        axis=1\n",
    "    )].index.tolist()\n",
    "\n",
    "    for i, start in enumerate(header_rows):\n",
    "        end = header_rows[i + 1] if i + 1 < len(header_rows) else len(raw_df)\n",
    "        block = raw_df.iloc[start:end].copy()\n",
    "        block.columns = block.iloc[0].astype(str).str.strip()\n",
    "        block = block[1:]\n",
    "        block = block.dropna(how='all')\n",
    "        block_dfs.append(block.reset_index(drop=True))\n",
    "\n",
    "    return block_dfs\n",
    "\n",
    "# ==== Upload Callback ====\n",
    "@app.callback(\n",
    "    [Output('file-status', 'children'),\n",
    "     Output('participant-dropdown', 'options'),\n",
    "     Output('block-dropdown', 'options'),\n",
    "     Output('compare-block-1', 'options'),\n",
    "     Output('compare-block-2', 'options')],\n",
    "    Input('upload-data', 'contents')\n",
    ")\n",
    "def handle_upload(contents):\n",
    "    global blocks, question_cols\n",
    "\n",
    "    if contents is None:\n",
    "        return \"No file uploaded yet.\", [], [], [], []\n",
    "\n",
    "    raw_df = parse_contents(contents)\n",
    "    block_list = split_blocks(raw_df)\n",
    "\n",
    "    score_map = {\"YES\": 1, \"Neither YES or NO\": 0.5, \"NO\": 0}\n",
    "    blocks = {}\n",
    "\n",
    "    for i, block in enumerate(block_list, start=1):\n",
    "        block.columns = block.columns.str.strip()\n",
    "        question_cols = [c for c in block.columns if str(c).startswith(\"Q\")]\n",
    "\n",
    "        for col in question_cols:\n",
    "            block[col] = block[col].map(score_map)\n",
    "\n",
    "        blocks[f\"Block {i}\"] = block\n",
    "\n",
    "    first_block = next(iter(blocks.values()))\n",
    "    participants = [{'label': n, 'value': n} for n in first_block['Full Name']]\n",
    "    block_options = [{'label': b, 'value': b} for b in blocks.keys()]\n",
    "\n",
    "    return \"File uploaded successfully!\", participants, block_options, block_options, block_options\n",
    "\n",
    "# ==== Main Dashboard ====\n",
    "@app.callback(\n",
    "    [Output('question-chart', 'figure'),\n",
    "     Output('group-grid', 'children'),\n",
    "     Output('development-lists', 'children')],\n",
    "    [Input('participant-dropdown', 'value'),\n",
    "     Input('block-dropdown', 'value')]\n",
    ")\n",
    "def update_dashboard(selected_name, selected_block):\n",
    "    if not selected_name or not selected_block:\n",
    "        return {}, \"\", \"\"\n",
    "\n",
    "    df = blocks[selected_block]\n",
    "    person_data = df[df['Full Name'] == selected_name].iloc[0]\n",
    "\n",
    "    scores = person_data[question_cols].values\n",
    "\n",
    "    bar_colors = []\n",
    "    for s in scores:\n",
    "        if s == 1:\n",
    "            bar_colors.append(\"#4CAF50\")\n",
    "        elif s == 0.5:\n",
    "            bar_colors.append(\"#F4A261\")\n",
    "        else:\n",
    "            bar_colors.append(\"#FF6B6B\")\n",
    "\n",
    "    fig = go.Figure()\n",
    "    fig.add_trace(go.Bar(x=question_cols, y=scores, marker_color=bar_colors))\n",
    "    fig.update_layout(title=f\"{selected_name} — {selected_block}\",\n",
    "                      xaxis_title=\"Questions\", yaxis_title=\"Score\",\n",
    "                      yaxis=dict(range=[0, 1]))\n",
    "\n",
    "    group_totals = [round(person_data[question_cols[i:i+4]].sum(), 2)\n",
    "                    for i in range(0, len(question_cols), 4)]\n",
    "\n",
    "    grid_items = [\n",
    "        html.Div([\n",
    "            html.Div(f\"{score}\", style={\"fontSize\": \"28px\", \"fontWeight\": \"bold\"}),\n",
    "            html.Div(label, style={\"fontSize\": \"12px\"})\n",
    "        ],\n",
    "        style={\n",
    "            \"backgroundColor\": get_colour(score),\n",
    "            \"padding\": \"20px\",\n",
    "            \"borderRadius\": \"8px\",\n",
    "            \"textAlign\": \"center\",\n",
    "            \"color\": \"black\"\n",
    "        })\n",
    "        for label, score in zip(GROUP_LABELS, group_totals)\n",
    "    ]\n",
    "\n",
    "    grid_layout = html.Div(grid_items, style={\n",
    "        \"display\": \"grid\",\n",
    "        \"gridTemplateColumns\": \"repeat(3, 1fr)\",\n",
    "        \"gap\": \"10px\",\n",
    "        \"marginBottom\": \"30px\"\n",
    "    })\n",
    "\n",
    "    half_scores = []\n",
    "    zero_scores = []\n",
    "\n",
    "    for q_col in question_cols:\n",
    "        q_num = int(q_col.replace(\"Q\", \"\"))\n",
    "        score = person_data[q_col]\n",
    "\n",
    "        if score == 0.5:\n",
    "            half_scores.append(f\"Q{q_num} – {QUESTION_TEXT[q_num]}\")\n",
    "        elif score == 0:\n",
    "            zero_scores.append(f\"Q{q_num} – {QUESTION_TEXT[q_num]}\")\n",
    "\n",
    "    lists_layout = [\n",
    "        html.Div([\n",
    "            html.H3(\"Scored 0.5 (Developing)\"),\n",
    "            html.Ul([html.Li(item) for item in half_scores])\n",
    "        ], style={\"width\": \"50%\"}),\n",
    "\n",
    "        html.Div([\n",
    "            html.H3(\"Scored 0 (Needs Attention)\"),\n",
    "            html.Ul([html.Li(item) for item in zero_scores])\n",
    "        ], style={\"width\": \"50%\"})\n",
    "    ]\n",
    "\n",
    "    return fig, grid_layout, lists_layout\n",
    "\n",
    "# ==== Comparison Callback ====\n",
    "@app.callback(\n",
    "    [Output('compare-grid-1', 'children'),\n",
    "     Output('compare-grid-2', 'children')],\n",
    "    [Input('participant-dropdown', 'value'),\n",
    "     Input('compare-block-1', 'value'),\n",
    "     Input('compare-block-2', 'value')]\n",
    ")\n",
    "def update_comparison(selected_name, block1, block2):\n",
    "    def make_grid(block_name):\n",
    "        if not selected_name or not block_name:\n",
    "            return \"\"\n",
    "\n",
    "        df = blocks[block_name]\n",
    "        person_data = df[df['Full Name'] == selected_name].iloc[0]\n",
    "\n",
    "        group_totals = [round(person_data[question_cols[i:i+4]].sum(), 2)\n",
    "                        for i in range(0, len(question_cols), 4)]\n",
    "\n",
    "        return html.Div([\n",
    "            html.Div([\n",
    "                html.Div(f\"{score}\", style={\"fontSize\": \"26px\", \"fontWeight\": \"bold\"}),\n",
    "                html.Div(label, style={\"fontSize\": \"11px\"})\n",
    "            ],\n",
    "            style={\n",
    "                \"backgroundColor\": get_colour(score),\n",
    "                \"padding\": \"18px\",\n",
    "                \"borderRadius\": \"8px\",\n",
    "                \"textAlign\": \"center\",\n",
    "                \"color\": \"black\"\n",
    "            })\n",
    "            for label, score in zip(GROUP_LABELS, group_totals)\n",
    "        ], style={\"display\": \"grid\", \"gridTemplateColumns\": \"repeat(3, 1fr)\", \"gap\": \"10px\", \"marginTop\": \"15px\"})\n",
    "\n",
    "    return make_grid(block1), make_grid(block2)\n",
    "\n",
    "import webbrowser\n",
    "webbrowser.open(\"http://127.0.0.1:8050/\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
